#!/usr/bin/env bash
# Stage 3 — ViralScan single-cell quant for SARS-CoV-2 covid_viralscan analysis
#
# Runs viralscan against the combined kallisto index (human + Serratus/anellovirus
# + SARS-CoV-2 NC_045512.2) built in Stage 2 (slurm_build_ref.sh).
#
# Two GEX samples run as a SLURM array (one task per sample):
#   Task 0 — LUM-SJ-x213-g  (batch 1)
#   Task 1 — LUM-SJ-x216-g  (batch 2)
#
# Submit after slurm_build_ref.sh completes:
#   sbatch --array=0-1 covid_viralscan/scripts/slurm_viralscan_quant.sh
#
#SBATCH -J covid_vs_quant
#SBATCH --array=0-1
#SBATCH --cpus-per-task=16
#SBATCH --mem=256G
#SBATCH --time=48:00:00
#SBATCH -o covid_viralscan/logs/quant_%A_%a.log
#SBATCH -e covid_viralscan/logs/quant_%A_%a.err

set -euo pipefail

# ── Sample table ──────────────────────────────────────────────────────────────
SAMPLES=("LUM-SJ-x213-g" "LUM-SJ-x216-g")
SAMPLE=${SAMPLES[$SLURM_ARRAY_TASK_ID]}

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO=/exports/para-lipg-hpc/mdmanurung/ViralScan
VS_CONDA_ENV=/exports/archive/hg-funcgenom-research/evonk/conda/envs/test_viralscan

export PATH="$VS_CONDA_ENV/bin:$PATH"
export PYTHONPATH="$REPO/src:${PYTHONPATH:-}"

FASTQ_ROOT=/exports/para-lipg-hpc/mdmanurung/covid_viralscan_fastqs/2025-3089-LUM-SJ-x213-x218-gtm/raw_fastq
GEX_DIR=$FASTQ_ROOT/${SAMPLE}_fastq
REF_DIR=$REPO/covid_viralscan/viralscan_ref
MERGED_DIR=$REPO/covid_viralscan/data/$SAMPLE
RESULTS_DIR=$REPO/covid_viralscan/results

# Viral-only GTFs for viralscan -gtf (accession listing / detection step)
#   viral_whole_genome.gtf = SARS-CoV-2 NC_045512.2 (generated by build-ref Step 1)
#   viral_genome.gtf       = full Serratus + anellovirus panel (2 313 sequences)
VIRAL_GTF_SARS2=$REF_DIR/viral/viral_whole_genome.gtf
VIRAL_GTF_SERRATUS=$REPO/references/starsolo/all_virus_serratus_plus_anellovirus/viral_genome.gtf

# 10x v3 whitelist (6 794 880 barcodes, 16 bp) — full correction list, not filtered cells
WHITELIST=$VS_CONDA_ENV/lib/python3.12/site-packages/ngs_tools/chemistry/whitelists/10x_version3_whitelist.txt.gz

mkdir -p "$MERGED_DIR" "$RESULTS_DIR" "$REPO/covid_viralscan/logs"

echo "[$(date)] Sample: $SAMPLE  (array task $SLURM_ARRAY_TASK_ID)"

# ── Verify prerequisites ───────────────────────────────────────────────────────
for f in "$REF_DIR/index.idx" "$REF_DIR/t2g.txt" \
          "$VIRAL_GTF_SARS2" "$VIRAL_GTF_SERRATUS" \
          "$WHITELIST" "$GEX_DIR"; do
    [[ -e "$f" ]] || { echo "ERROR: missing $f" >&2; exit 1; }
done
command -v python || { echo "ERROR: python not on PATH" >&2; exit 1; }

echo "[$(date)] Prerequisites OK."
echo "  Index:   $REF_DIR/index.idx  ($(du -sh "$REF_DIR/index.idx" | cut -f1))"
echo "  T2G:     $REF_DIR/t2g.txt    ($(wc -l < "$REF_DIR/t2g.txt") lines)"
echo "  GEX dir: $GEX_DIR"

# ── Step 1: Collect R1 / R2 files for this sample ────────────────────────────
mapfile -t R1_FILES < <(find "$GEX_DIR" -name "*_R1_001.fastq.gz" | sort)
mapfile -t R2_FILES < <(find "$GEX_DIR" -name "*_R2_001.fastq.gz" | sort)

[[ ${#R1_FILES[@]} -gt 0 ]] || { echo "ERROR: no R1 files found in $GEX_DIR" >&2; exit 1; }
[[ ${#R1_FILES[@]} -eq ${#R2_FILES[@]} ]] || {
    echo "ERROR: R1/R2 count mismatch (${#R1_FILES[@]} R1, ${#R2_FILES[@]} R2)" >&2
    exit 1
}
echo "[$(date)] Found ${#R1_FILES[@]} lane(s):"
for i in "${!R1_FILES[@]}"; do
    echo "  Lane $((i+1)): $(basename "${R1_FILES[$i]}")  /  $(basename "${R2_FILES[$i]}")"
done

# ── Step 2: Concatenate lanes ─────────────────────────────────────────────────
# cat on .fastq.gz produces a valid multi-stream gzip consumed correctly by
# gzip, zcat, pigz, and kb-python / kallisto.
MERGED_R1=$MERGED_DIR/${SAMPLE}_merged_R1.fastq.gz
MERGED_R2=$MERGED_DIR/${SAMPLE}_merged_R2.fastq.gz

if [[ -f "$MERGED_R1" && -f "$MERGED_R2" ]]; then
    echo "[$(date)] SKIP lane merge — merged R1/R2 already exist."
    echo "  R1: $(du -sh "$MERGED_R1" | cut -f1)   R2: $(du -sh "$MERGED_R2" | cut -f1)"
else
    if [[ ${#R1_FILES[@]} -eq 1 ]]; then
        echo "[$(date)] Single-lane input — symlinking instead of copying."
        ln -sf "${R1_FILES[0]}" "$MERGED_R1"
        ln -sf "${R2_FILES[0]}" "$MERGED_R2"
    else
        echo "[$(date)] Merging ${#R1_FILES[@]} lanes (cat gzip streams) ..."
        cat "${R1_FILES[@]}" > "$MERGED_R1"
        cat "${R2_FILES[@]}" > "$MERGED_R2"
        echo "[$(date)] Lane merge done."
        echo "  R1: $(du -sh "$MERGED_R1" | cut -f1)   R2: $(du -sh "$MERGED_R2" | cut -f1)"
    fi
fi

# Quick sanity check: R1 read length should be 28 bp (16 CB + 12 UMI) for 10x 5′ v3.
# NB: `zcat | head` closes the pipe early on large FASTQs, so zcat dies with SIGPIPE
# (exit 141). Under `set -euo pipefail` that would abort the whole job, so capture via
# command substitution guarded with `|| true` — the read length is already emitted by
# awk before the SIGPIPE propagates.
echo "[$(date)] Sanity — first R1 read length (expect 28 bp for 10x 5′ v3):"
READLEN=$(zcat "$MERGED_R1" 2>/dev/null | head -2 | tail -1 | awk '{print length($0)}') || true
echo "  ${READLEN:-unknown} bp"

# ── Step 3: viralscan quant ────────────────────────────────────────────────────
SENTINEL="$RESULTS_DIR/$SAMPLE/log/kb.done"

if [[ -f "$SENTINEL" ]]; then
    echo "[$(date)] SKIP viralscan quant — sentinel exists: $SENTINEL"
else
    echo "[$(date)] Running viralscan quant (cores: $SLURM_CPUS_PER_TASK) ..."
    python "$REPO/src/viralscan/menu.py" \
        -i "$REF_DIR/index.idx" \
        -t "$REF_DIR/t2g.txt" \
        -gtf "$VIRAL_GTF_SARS2,$VIRAL_GTF_SERRATUS" \
        -o "$RESULTS_DIR" \
        -s1 "$MERGED_R1" \
        -s2 "$MERGED_R2" \
        -x 10xv3 \
        -w "$WHITELIST" \
        -c "$SLURM_CPUS_PER_TASK" \
        --multimap-method host-conservative \
        --yes
    echo "[$(date)] viralscan quant complete."
fi

echo "[$(date)] Stage 3 done."
echo "  Results: $RESULTS_DIR/$SAMPLE"
echo ""
echo "Next steps:"
echo "  1. Check $RESULTS_DIR/$SAMPLE/kb-python/run_info.json for % reads pseudoaligned"
echo "  2. Look for NC_045512.2 row in viral_summary.tsv (SARS-CoV-2)"
echo "  3. Compare against NC_004718.3 row (SARS-CoV-1 in Serratus panel — expected negative)"
echo "  4. Intersect detected barcodes with called cells from CellRanger"
