"""Shared constants for ViralScan.

The ``VIRUS_NAME_MAP`` dictionary maps the abbreviated prefix used in the
bundled GTF gene IDs to the human-readable virus name. It used to be
duplicated verbatim in ``detection.py`` and ``umap.py``; both modules now
import it from here.
"""

VIRUS_NAME_MAP = {
    "AICHI": "Aichi virus",
    "AUSBATLYSSA": "Australian Bat Lyssavirus",
    "BANNA": "Banna virus",
    "BARMAH": "Barmah forest virus",
    "BKPOLY": "BK polyomavirus",
    "BUNYAMW": "Bunyamwera virus",
    "BUNYA": "Bunyavirus La Crosse",
    "CERC_HERP": "Cercopithecine herpesvirus",
    "CHIKUNG": "Chikungunya virus",
    "COSA_A": "Cosavirus A",
    "COWPOX": "Cowpox virus",
    "COXSACKIE": "Coxsackievirus",
    "CRIMEAN": "Crimean Congo hemorrhagic fever virus",
    "EQUINE_ENCE": "Eastern_equine_encephalitis_virus",
    "EBOLA": "Ebolavirus",
    "ECHO": "Echovirus",
    "ENCEPHAL": "Encephalomyocarditis virus",
    "EPSTEIN": "Epstein-Barr virus",
    "EURBATLYSSA": "European bat lyssavirus",
    "GB": "GB virus C_Hepatitis G virus",
    "HANTAAN": "Hantaan virus",
    "HENDRA": "Hendra virus",
    "HEP_A": "Hepatitis A virus",
    "HEP_B": "Hepatitis B virus",
    "HEP_C": "Hepatitis C virus",
    "HEP_DELTA": "Hepatitis delta virus",
    "HEP_E": "Hepatitis E virus",
    "HUM_ADENO": "Human adenovirus",
    "HUM_ASTRO": "Human astrovirus",
    "HUM_COR": "Human coronavirus",
    "HUM_CYTO": "Human cytomegalovirus",
    "HUM_ENTERO": "Human enterovirus 68, 70",
    "HUM_HERP1": "Human herpesvirus 1",
    "HUM_HERP2": "Human herpesvirus 2",
    "HUM_HERP6B": "Human herpesvirus 6b",
    "HUM_HERP6": "Human herpesvirus 6",
    "HUM_HERP7": "Human herpesvirus 7",
    "HUM_HERP8": "Human herpesvirus 8",
    "HUM_PAP_1618": "Human papillomavirus 16,18",
    "HUM_PAP_1": "Human papillomavirus 1",
    "HUM_PAP_2": "Human papillomavirus 2",
    "HUM_PARA": "Human parainfluenza",
    "HUM_PARVO": "Human parvovirus B19",
    "HUM_RESP": "Human respiratory syncytial virus",
    "HUM_RHINO": "Human rhinovirus",
    "HUM_SARS": "Human SARS coronavirus",
    "INFL_A": "Influenza A virus",
    "INFL_B": "Influenza B virus",
    "INFL_C": "Influenza C virus",
    "JAP_ENCE": "Japanese encephalitis virus",
    "JC_POLY": "JC polyomavirus",
    "KI_POLY": "KI Polyomavirus",
    "LAKE_VIC": "Lake Victoria marburgvirus",
    "LANGAT": "Langat virus",
    "LASSA": "Lassa virus",
    "LOUPING": "Louping ill virus",
    "LYMPH": "Lymphocytic choriomeningitis virus",
    "MAYARO": "Mayaro virus",
    "MEASLES": "Measles virus",
    "MERKEL": "Merkel cell polyomavirus",
    "MERS": "MERS coronavirus",
    "MOLLU": "Molluscum contagiosum virus",
    "MONKEYPOX": "Monkeypox virus",
    "MUMPS": "Mumps virus",
    "MUR_VAL": "Murray valley encephalitis virus",
    "NIPAH": "Nipah virus",
    "NORWALK": "Norwalk virus",
    "ORF": "Orf virus",
    "OROPOU": "Oropouche virus",
    "ONYONG": "O�nyong-nyong virus",
    "POLIO": "Poliovirus",
    "RABIES": "Rabies virus",
    "ROSA_A": "Rosavirus A",
    "ROSS_RIVER": "Ross river virus",
    "ROTA_A": "Rotavirus A",
    "ROTA_B": "Rotavirus B",
    "ROTA_C": "Rotavirus C",
    "RUBELLA": "Rubella virus",
    "SALI_A": "Salivirus A",
    "SAPPORO": "Sapporo virus",
    "SEMLIKI": "Semliki forest virus",
    "SEOUL": "Seoul virus",
    "SINDBIS": "Sindbis virus",
    "ST_LOUIS": "St. louis encephalitis virus",
    "TICK": "Tick-borne powassan virus",
    "TTV": "Torque teno virus",
    "TOSCANA": "Toscana virus",
    "VACCINIA": "Vaccinia virus",
    "VARICELLA": "Varicella-zoster virus",
    "VARIOLA": "Variola virus",
    "VEN_EQU": "Venezuelan equine encephalitis virus",
    "VES_STOM": "Vesicular stomatitis virus",
    "WES_EQU": "Western equine encephalitis virus",
    "WES_NILE": "West Nile virus",
    "WU_POLY": "WU polyomavirus",
    "YABA": "Yaba-like disease virus",
    "YELLOW": "Yellow fever virus",
    "ZIKA": "Zika virus",
}
