"""Layer 2: infer a viral gene programme (latent vs productive) for detected viruses.

Layer 1 answers *is the virus here and how much*. This module answers *what is
the virus doing* — and only for viruses layer 1 detected, and only where the
assay can support the answer.

Why a second layer, and why it is built this way
------------------------------------------------
The obvious implementation is to sum the latent genes, sum the lytic genes, and
compare. Measured on the bundled EBV LCL run (``SRR12682296``), which is
latently infected by construction, that gives:

    LATENT (10 genes)  236,342     LYTIC (12 genes)  247,633
      BNLF2a   49,662                 BHLF1   142,954   <- highest EBV gene
      LMP-1    50,237                 BMRF1    45,005
      BaRF1.1  46,956                 BBLF2/3  13,246
      BNLF2b   45,108                 BRLF1     9,560
      EBNA-1.1    920  <-             BZLF1     9,308

A latent:lytic aggregate ratio of 1.15 in a cell line defined by latency is not
biology. EBNA-1 is expressed from every latent episome and must be present in
every infected cell, yet it sits ~155x below BHLF1. The cause is pervasive
overlapping-ORF cross-mapping: EBV's latent transcripts are transcribed from a
region densely packed with nested and antisense lytic ORFs, so reads cross-map
in both directions. Per-gene **aggregate totals are therefore uninformative**,
and no amount of care applied to them recovers a latent/lytic answer.

The per-marker breakdown on that same run shows the mechanism directly.
Correction (2026-09-27): BARF1 is latent only in epithelial cancers and
BaRF1.1 is the lytic ribonucleotide reductase, so both have left the
catalogue (2026-10-02: BNLF2a/b and BHRF1 are early lytic and also left); the
figures below include them and are under re-verification (PLAN PROG-07):

    marker            programme    unique   allocated
    BARF1.2           latent         13,668          0
    BNLF2a            latent              0     49,662
    BNLF2b            latent              0     45,108
    BZLF1             productive          0      9,308
    BMRF1             productive          0     45,005
    BcLF1             productive      6,609          59

The uniquely-placing layer puts **zero** molecules on BZLF1 — the canonical lytic
marker — which is the correct answer for a latent cell line, and puts 13,668 on
BARF1.2 where the allocated layer put none. Cross-mapping moves latent signal
onto lytic ORFs and back again.

Two defences follow, and it is worth being precise about what each buys:

1. **Breadth over distinct overlap groups, never a gene count.** Two nested lytic
   ORFs are one piece of evidence. In EBV the whole latent EBNA locus
   (EBNA-1, EBNA-2, EBNA-LP) is one group, and BTRF1 shares a group with BcLF1.
   This is what makes the *aggregate* comparison unneeded.
2. **Uniquely-placing evidence.** Per-cell breadth calling is directionally
   consistent on both layers — on the real run the two never disagree in the
   dangerous direction (0 cells go latent-on-unique to productive-on-allocated).
   What the unique layer buys is **sensitivity**: 695 cells called latent
   versus 526 on the allocated layer (PROG-07, 2026-10-03), because 217 latent
   cells turn ``mixed`` there once cross-mapping adds lytic evidence. The
   failure mode is lost sensitivity, not an inverted call.

A third defence is about honesty rather than arithmetic:

3. **No absence claim from a thin anchor set.** A virus whose latency side is a
   single transcript (HSV-1's LAT) cannot support "not detected, therefore
   latent", so ``latency_observable_in_rna`` is false for it and the ``latent``
   state is unreachable.

Scope note
----------
This is fundamentally a *transcriptomic* assay. DNA-level latency is invisible
here: a silent HIV provirus, a transcriptionally silent integrated HPV genome
and a HBV cccDNA pool all produce no reads. For those, "latent" is not an
available answer and this module says so rather than guessing.

Catalogue
---------
``src/viralscan/data/gene_programs.tsv``, generated by
``extras/build_gene_programs.py``. The biology is hand-curated; the panel
attributes and overlap groups are computed. Nine viruses: four with a complete
latency and reactivation split, five partial and flagged as such.
"""

from __future__ import annotations

import csv
import importlib.resources
import os
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import pandas as pd
    from scipy import sparse

#: Gene-programme values in the catalogue.
PROGRAMMES = frozenset({"latent", "productive"})

#: Per-cell states this module may emit.
#:
#: ``latent`` and ``mixed`` are unreachable when
#: :attr:`Marker` set's virus declares ``latency_observable_in_rna=false``.
#: ``reactivating`` (PLAN PROG-12) is immediate-early-only evidence: productive
#: markers carry molecules, every one of them is immediate-early, and the cell
#: is not already ``productive``/``mixed``/``latent``. It only ever replaces
#: what would otherwise be ``indeterminate``, so adding it moves none of the
#: other counts.
STATES = frozenset({"productive", "latent", "reactivating", "mixed", "indeterminate"})

#: Viruses for which ``reactivating`` is not applicable (PLAN PROG-12). HCMV
#: latency has no restricted programme: it mirrors late-lytic expression at much
#: lower levels (PMID 29535194), and UL122/UL123 are immediate-early yet
#: detectable in latently infected cells, so a presence-based immediate-early
#: call is not specific. These viruses never emit the state and report
#: ``not_applicable`` in the summary. Keyed by the catalogue ``virus`` name.
REACTIVATION_NOT_APPLICABLE = frozenset({"Human cytomegalovirus"})

#: Allowed ``kinetic_class`` values in the catalogue. ``unclassified`` means no
#: primary source classifying the marker was retrieved; it is never a guess.
KINETIC_CLASSES = frozenset(
    {"latent", "immediate_early", "early", "leaky_late", "late", "unclassified"}
)

#: Which catalogue column holds the gene ID for each panel form.
PANEL_FORM_COLUMN = {
    "bundled": "gene_id_bundled",
    "merged": "gene_id_merged",
    "starsolo": "gene_id_starsolo",
}

_TSV_FILENAME = "gene_programs.tsv"
_PACKAGE_DATA = "viralscan.data"

#: The evidence layer layer 2 trusts. Named here so the report and the TSV
#: cannot disagree about which numbers produced a call. On the EBV LCL run
#: (PROG-07, 2026-10-03) this yields 695 latent cells against 526 on the
#: allocated layer, with zero cells inverted between the two.
EVIDENCE_LAYER = "counts_unique_viral"

Row = dict[str, Any]


def _default_tsv_path() -> Path:
    """Return the packaged catalogue via importlib.resources.

    Mirrors ``anellovirus._default_tsv_path`` so both packaged tables resolve
    the same way regardless of how the package was installed.
    """
    return Path(str(importlib.resources.files(_PACKAGE_DATA).joinpath(_TSV_FILENAME)))


def load_catalogue(path: str | Path | None = None) -> list[Row]:
    """Load the gene-programme catalogue.

    Returns one dict per marker gene, with every TSV column as a string. The
    boolean-ish columns (``has_cds``, ``non_overlapping``,
    ``available_in_starsolo``, ``do_not_normalise``,
    ``latency_observable_in_rna``) are kept as the strings ``"true"``/``"false"``
    rather than coerced, so a malformed value is visible in the raw row rather
    than silently becoming ``False``.
    """
    tsv_path = Path(path) if path is not None else _default_tsv_path()
    rows: list[Row] = []
    with open(tsv_path, newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            rows.append(dict(row))
    return rows


def validate_catalogue(rows: list[Row]) -> list[str]:
    """Return a list of problems with ``rows``; empty means valid.

    Checks the controlled vocabularies, the boolean columns, that every gene ID
    form is populated, and that no ``(virus, gene, programme)`` triple repeats.
    Deliberately does *not* check the panel: that is the build script's job and
    is covered by a test against the real GTFs, which are not available at
    runtime.
    """
    errors: list[str] = []
    if not rows:
        return ["gene-programme catalogue is empty"]
    bool_columns = (
        "latency_observable_in_rna",
        "has_cds",
        "non_overlapping",
        "available_in_starsolo",
        "do_not_normalise",
    )
    seen: set[tuple[str, str, str]] = set()
    for index, row in enumerate(rows, start=2):  # +1 header, 1-based
        where = f"row {index}"
        for column in ("virus", "programme", "gene_id_bundled", "overlap_group"):
            if not str(row.get(column, "")).strip():
                errors.append(f"{where}: {column} is empty")
        if row.get("programme") not in PROGRAMMES:
            errors.append(
                f"{where}: programme {row.get('programme')!r} not in {sorted(PROGRAMMES)}"
            )
        if "kinetic_class" in row and row["kinetic_class"] not in KINETIC_CLASSES:
            errors.append(f"{where}: kinetic_class {row['kinetic_class']!r} invalid")
        if row.get("panel_completeness") not in {"complete", "partial", "not_applicable"}:
            errors.append(f"{where}: panel_completeness {row.get('panel_completeness')!r} invalid")
        for column in bool_columns:
            if row.get(column) not in {"true", "false"}:
                errors.append(f"{where}: {column}={row.get(column)!r} is not true/false")
        for column in ("gene_id_merged", "gene_id_starsolo"):
            if not str(row.get(column, "")).strip():
                errors.append(f"{where}: {column} is empty")
        key = (row.get("virus", ""), row.get("gene_id_bundled", ""), row.get("programme", ""))
        if key in seen:
            errors.append(f"{where}: duplicate (virus, gene, programme) {key}")
        seen.add(key)
    return errors


@dataclass(frozen=True)
class Marker:
    """One catalogue marker resolved to a column of the count matrix.

    ``overlap_group`` identifies the set of mutually overlapping genes this
    marker shares sequence with. Two markers in the same group are one piece of
    evidence, not two, so breadth is counted in groups.
    """

    var_name: str
    programme: str
    overlap_group: str
    non_overlapping: bool
    has_cds: bool
    kinetic_class: str = "unclassified"

    @property
    def is_productive(self) -> bool:
        return self.programme == "productive"


@dataclass(frozen=True)
class UnresolvedMarker:
    """A catalogue row that could not be matched to a count-matrix column."""

    refseq_gene: str
    gene_id: str
    reason: str


def resolve_markers(
    virus: str,
    var_names: Iterable[str],
    panel_form: str = "bundled",
    catalogue: list[Row] | None = None,
    identity: Any = None,
) -> tuple[list[Marker], list[UnresolvedMarker]]:
    """Resolve ``virus``'s catalogue rows to columns of the count matrix.

    Parameters
    ----------
    virus:
        A ``virus_key`` (``taxid:10376``) or the virus display name, when
        ``identity`` is given; otherwise the display name as produced by
        ``virus_grouping``, which must match the catalogue's ``virus`` column
        exactly.
    identity:
        The Run's :class:`~viralscan.virus_identity.VirusIdentityTable`. With it
        the lookup is by ``virus_key``: the catalogue's ``virus`` names are
        mapped to keys through the table, so a label that differs between the
        two still selects the right rows.
    var_names:
        The count matrix's ``var_names`` (an ``Index``, list, or any iterable of
        strings). Only membership is used, so this is cheap.
    panel_form:
        ``"bundled"``, ``"merged"`` or ``"starsolo"`` — which catalogue ID column
        to try first. The other forms are tried as a fallback, because a run may
        have been indexed from any panel and the catalogue is additive rather
        than exclusive.
    catalogue:
        Override for tests; defaults to the packaged catalogue.

    Returns
    -------
    ``(resolved, unresolved)``

    Notes
    -----
    Gene IDs are matched by **exact string equality only**. Zero-padding is never
    normalised, because HHV-6A uses two padding widths for genuinely different
    ORFs (``HHV6gp041`` is U43, ``HHV6gp41`` is U42, and six further pairs
    differ). Normalising would silently merge distinct genes.

    Markers flagged ``available_in_starsolo=false`` are skipped under
    ``panel_form="starsolo"`` and reported as unresolved with a reason, rather
    than dropped in silence. Those are the genes the STARsolo packager rewrites
    to a bare ``unassigned_gene_N`` shared by seven or more genomes.
    """
    if panel_form not in PANEL_FORM_COLUMN:
        raise ValueError(
            f"panel_form must be one of {sorted(PANEL_FORM_COLUMN)}, got {panel_form!r}"
        )
    rows = catalogue if catalogue is not None else load_catalogue()
    available = set(var_names)
    wanted_key = None
    key_of_name: dict[str, str] = {}
    if identity is not None:
        key_to_name = identity.virus_names()
        key_of_name = {name: key for key, name in key_to_name.items()}
        wanted_key = virus if virus in key_to_name else key_of_name.get(virus)

    # Try the requested form first, then the others as a fallback.
    order = [panel_form] + [f for f in PANEL_FORM_COLUMN if f != panel_form]
    resolved: list[Marker] = []
    unresolved: list[UnresolvedMarker] = []
    for row in rows:
        if wanted_key is not None:
            if key_of_name.get(row.get("virus", "")) != wanted_key:
                continue
        elif row.get("virus") != virus:
            continue
        if panel_form == "starsolo" and row.get("available_in_starsolo") == "false":
            unresolved.append(
                UnresolvedMarker(
                    refseq_gene=row.get("refseq_gene", ""),
                    gene_id=row.get("gene_id_starsolo", ""),
                    reason=(
                        "not attributable under STARsolo: the packager rewrites "
                        f"{row.get('gene_id_bundled')} to a bare "
                        f"{row.get('gene_id_starsolo')} shared by >=7 genomes"
                    ),
                )
            )
            continue
        hit = None
        for form in order:
            candidate = row.get(PANEL_FORM_COLUMN[form], "")
            if candidate and candidate in available:
                hit = candidate
                break
        if hit is None:
            unresolved.append(
                UnresolvedMarker(
                    refseq_gene=row.get("refseq_gene", ""),
                    gene_id=row.get(PANEL_FORM_COLUMN[panel_form], ""),
                    reason=(
                        "no catalogue gene-ID form for this panel matches a column "
                        "of the count matrix"
                    ),
                )
            )
            continue
        resolved.append(
            Marker(
                var_name=hit,
                programme=row["programme"],
                overlap_group=row["overlap_group"],
                non_overlapping=row.get("non_overlapping") == "true",
                has_cds=row.get("has_cds") == "true",
                kinetic_class=row.get("kinetic_class") or "unclassified",
            )
        )
    return resolved, unresolved


def _nonzero_columns(matrix: sparse.csr_matrix | None, cell: int, min_umi: float = 0.0) -> set[int]:
    """Column indices carrying evidence in ``cell`` of a CSR ``matrix``.

    A column counts when its value is positive and at least ``min_umi``. The
    default ``0`` means any nonzero value, which is what every call before
    PROG-12 used; it must stay that way because the multimap-allocated layer
    holds fractional values that a floor of 1 would silently drop.
    """
    if matrix is None:
        return set()
    start, end = matrix.indptr[cell], matrix.indptr[cell + 1]
    return {
        int(matrix.indices[offset])
        for offset in range(start, end)
        if matrix.data[offset] > 0 and matrix.data[offset] >= min_umi
    }


def _breadth(
    nonzero: set[int],
    columns: list[int],
    groups: dict[int, str],
) -> int:
    """Distinct overlap groups carrying at least one molecule.

    Markers sharing an ``overlap_group`` collapse to one, which is what makes a
    nested pair count once. ``non_overlapping`` is deliberately *not* consulted
    here: a group of mutually overlapping genes is one locus regardless of how
    many ORFs RefSeq split it into, so the group is the unit and the flag is
    carried only for reporting.
    """
    return len({groups[c] for c in columns if c in nonzero})


def _decide(
    prod: int,
    lat: int,
    min_breadth: int,
    latency_observable: bool,
    latent_min_breadth: int = 1,
    ie_only: bool = False,
) -> str:
    latent_called = lat >= latent_min_breadth and latency_observable
    if prod >= min_breadth and latent_called:
        return "mixed"
    if prod >= min_breadth:
        return "productive"
    if latent_called:
        return "latent"
    if ie_only:
        return "reactivating"
    return "indeterminate"


def call_cell_programme(
    unique_matrix: sparse.csr_matrix,
    markers: list[Marker],
    *,
    min_breadth: int = 2,
    latency_observable: bool = True,
    selected_matrix: sparse.csr_matrix | None = None,
    cell_index: int | None = None,
    latent_min_breadth: int = 1,
    min_umi: float = 0.0,
    reactivating_applicable: bool = True,
) -> list[dict[str, Any]]:
    """Assign a gene-programme state to each cell.

    Parameters
    ----------
    unique_matrix:
        ``(cells x len(markers))`` CSR matrix of **uniquely-placing** viral
        molecules, from ``adata.layers["counts_unique_viral"]`` subset to the
        marker columns. Columns correspond **positionally** to ``markers``.
    markers:
        Resolved markers, in the same order as the matrix columns.
    min_breadth:
        Distinct overlap groups required before a programme is called. Must be
        >= 1.
    latency_observable:
        Whether the virus's latency anchor set is thick enough to support an
        absence claim. When false, ``latent`` and ``mixed`` are unreachable and
        every call carries ``latency_not_observable=True``.
    selected_matrix:
        Optional multimap-allocated matrix, same shape. The same decision is
        applied to it and returned as ``selected_state``, which never influences
        ``state``. This is the comparison that makes the design legible: on the
        EBV LCL run the selected layer puts 9,308 molecules on BZLF1 — the
        canonical lytic marker — where the unique layer has **zero**, because a
        latent cell line expresses no BZLF1.
    cell_index:
        When given, return a single dict for that cell instead of one per cell.
    latent_min_breadth:
        Distinct latent overlap groups required for ``latent``/``mixed`` (PLAN
        PROG-12). Must be >= 1; the default 1 is the pre-PROG-12 rule.
    min_umi:
        Per-marker floor: a marker counts only when its value is at least this
        (and positive). Must be >= 0; the default 0 is any nonzero value, the
        pre-PROG-12 rule.
    reactivating_applicable:
        When false the ``reactivating`` state is never emitted (see
        :data:`REACTIVATION_NOT_APPLICABLE`). It is defined over *productive*
        markers only: a latent marker's kinetic class never makes a cell
        reactivating.

    Returns
    -------
    list of dicts with ``state``, ``productive_breadth``, ``latent_breadth``,
    ``selected_state``, ``selected_productive_breadth``,
    ``selected_latent_breadth``, ``evidence_layer`` and
    ``latency_not_observable``.
    """
    if min_breadth < 1:
        raise ValueError(
            f"min_breadth must be >= 1, got {min_breadth}. A breadth of zero "
            "would call every cell productive on no evidence at all."
        )
    if latent_min_breadth < 1:
        raise ValueError(f"latent_min_breadth must be >= 1, got {latent_min_breadth}.")
    if min_umi < 0:
        raise ValueError(f"min_umi must be >= 0, got {min_umi}.")
    groups = {i: m.overlap_group for i, m in enumerate(markers)}
    productive_cols = [i for i, m in enumerate(markers) if m.is_productive]
    later_cols = [i for i in productive_cols if markers[i].kinetic_class != "immediate_early"]
    latent_cols = [i for i, m in enumerate(markers) if m.programme == "latent"]

    indices = [cell_index] if cell_index is not None else range(unique_matrix.shape[0])

    calls: list[dict[str, Any]] = []
    for cell in indices:
        nonzero = _nonzero_columns(unique_matrix, cell, min_umi)
        prod = _breadth(nonzero, productive_cols, groups)
        lat = _breadth(nonzero, latent_cols, groups)
        ie_only = (
            reactivating_applicable and prod >= 1 and _breadth(nonzero, later_cols, groups) == 0
        )
        state = _decide(prod, lat, min_breadth, latency_observable, latent_min_breadth, ie_only)

        sel_prod = sel_lat = sel_state = None
        if selected_matrix is not None:
            sel_nonzero = _nonzero_columns(selected_matrix, cell, min_umi)
            sel_prod = _breadth(sel_nonzero, productive_cols, groups)
            sel_lat = _breadth(sel_nonzero, latent_cols, groups)
            sel_ie_only = (
                reactivating_applicable
                and sel_prod >= 1
                and _breadth(sel_nonzero, later_cols, groups) == 0
            )
            sel_state = _decide(
                sel_prod,
                sel_lat,
                min_breadth,
                latency_observable,
                latent_min_breadth,
                sel_ie_only,
            )

        assert state in STATES, state
        if sel_state is not None:
            assert sel_state in STATES, sel_state
        calls.append(
            {
                "state": state,
                "productive_breadth": prod,
                "latent_breadth": lat,
                "selected_state": sel_state,
                "selected_productive_breadth": sel_prod,
                "selected_latent_breadth": sel_lat,
                "evidence_layer": EVIDENCE_LAYER,
                "latency_not_observable": not latency_observable,
            }
        )
    return calls


def summarise_programs(
    cells_df: pd.DataFrame | None,
    catalogue: list[Row],
    *,
    min_breadth: int = 2,
    viruses: Iterable[str] | None = None,
    latent_min_breadth: int = 1,
    min_umi: float = 0.0,
    marker_resolution: dict[str, dict[str, int]] | None = None,
) -> pd.DataFrame:
    """Roll per-cell calls up to one row per virus.

    Every virus in ``viruses`` gets a row, whether or not it produced any
    per-cell call, and whether or not it has a catalogue entry. A virus detected
    by layer 1 with no marker evidence must not vanish: a reader has to be able
    to tell "detected, programme not assessable" from "never looked at". The
    first reports ``panel_completeness`` with zero state counts and a caveat; the
    second reports ``not_applicable``.

    ``marker_resolution`` (``{virus: {"resolved": n, "unresolved": m}}``, from
    ``run_one``) fills ``n_markers_resolved`` / ``n_markers_unresolved`` and
    selects the caveat: catalogue markers that did not resolve against the
    index (PLAN ``PROG-14``) are reported as such, not as a molecule-placement
    problem.
    """
    import pandas as pd

    facts: dict[str, dict[str, Any]] = {}
    for row in catalogue:
        facts.setdefault(row["virus"], {})
        facts[row["virus"]]["panel_completeness"] = row["panel_completeness"]
        facts[row["virus"]]["latency_observable_in_rna"] = (
            row["latency_observable_in_rna"] == "true"
        )

    if cells_df is None or len(cells_df) == 0:
        groups: dict[str, Any] = {}
        seen: list[str] = []
    else:
        # A no-model virus gets one placeholder row with an empty barcode; it
        # marks the virus, it is not a cell (PLAN PROG-19).
        real = cells_df["barcode"].fillna("").astype(str) != ""
        groups = dict(tuple(cells_df[real].groupby("virus_name", sort=True)))
        seen = sorted(set(cells_df["virus_name"]))

    ordered: list[str] = list(viruses) if viruses is not None else list(seen)
    for name in seen:
        if name not in ordered:
            ordered.append(name)

    rows: list[dict[str, Any]] = []
    for virus in ordered:
        group = groups.get(virus)
        info = facts.get(virus)
        if info is None:
            completeness = "not_applicable"
            observable = False
            caveat = "no programme model defined for this virus"
        else:
            completeness = info["panel_completeness"]
            observable = info["latency_observable_in_rna"]
            caveat = (
                ""
                if completeness == "complete"
                else (
                    "panel_completeness=partial: the latency anchor set is too thin to "
                    "support an absence claim, so 'latent' is unreachable for this virus"
                )
            )
        res = (marker_resolution or {}).get(virus)
        n_res = res["resolved"] if res else None
        n_unres = res["unresolved"] if res else None
        if info is not None and res and n_unres:
            n_cat = res["resolved"] + res["unresolved"]
            caveat = "; ".join(
                filter(
                    None,
                    [
                        caveat,
                        f"none of {n_cat} catalogue markers resolved against this index "
                        "(reference and catalogue disagree), so no programme could be assessed"
                        if not n_res
                        else f"{n_unres} of {n_cat} catalogue markers did not resolve against "
                        "this index; calls use the reduced marker set and panel_completeness "
                        "describes the catalogue, not this index",
                    ],
                )
            )
        if group is None:
            if info is not None and not (res and not n_res and n_unres):
                caveat = "; ".join(
                    filter(
                        None,
                        [
                            caveat,
                            "detected by layer 1 but no catalogue marker carried uniquely-"
                            "placing molecules, so no programme could be assessed",
                        ],
                    )
                )
            counts: dict[str, int] = {}
            n_total = 0
            prod_med = lat_med = sel_prod_med = sel_lat_med = 0.0
            n_prod_sel = n_lat_sel = 0
        else:
            counts = group["state"].value_counts().to_dict()
            n_total = int(len(group))
            prod_med = _median_where(group, "state", "productive", "productive_breadth")
            lat_med = _median_where(group, "state", "latent", "latent_breadth")
            sel_prod_med = _fill_median(group, "selected_productive_breadth")
            sel_lat_med = _fill_median(group, "selected_latent_breadth")
            sel_counts = (
                group["selected_state"].value_counts().to_dict()
                if "selected_state" in group.columns
                else {}
            )
            n_prod_sel = int(sel_counts.get("productive", 0))
            n_lat_sel = int(sel_counts.get("latent", 0)) if observable else 0

        rows.append(
            {
                "virus_name": virus,
                "n_cells_total": n_total,
                "n_cells_productive": int(counts.get("productive", 0)),
                "n_cells_latent": 0 if not observable else int(counts.get("latent", 0)),
                "n_cells_reactivating": "not_applicable"
                if virus in REACTIVATION_NOT_APPLICABLE
                else int(counts.get("reactivating", 0)),
                "n_cells_mixed": 0 if not observable else int(counts.get("mixed", 0)),
                "n_cells_indeterminate": int(counts.get("indeterminate", 0)),
                "n_cells_productive_selected_layer": n_prod_sel,
                "n_cells_latent_selected_layer": n_lat_sel,
                "productive_breadth_median": prod_med,
                "latent_breadth_median": lat_med,
                "selected_productive_breadth_median": sel_prod_med,
                "selected_latent_breadth_median": sel_lat_med,
                "panel_completeness": completeness,
                "latency_observable_in_rna": observable,
                "evidence_layer": EVIDENCE_LAYER,
                "min_breadth": min_breadth,
                "latent_min_breadth": latent_min_breadth,
                "marker_min_umi": min_umi,
                "n_markers_resolved": n_res,
                "n_markers_unresolved": n_unres,
                "caveat": caveat,
            }
        )
    return pd.DataFrame(rows)


def _fill_median(group: pd.DataFrame, column: str) -> float:
    if column not in group.columns:
        return 0.0
    series = pd_numeric(group[column]).fillna(0.0)
    return float(series.median()) if len(series) else 0.0


def _median_where(group: pd.DataFrame, state_column: str, state: str, value_column: str) -> float:
    subset = group.loc[group[state_column] == state]
    if subset.empty or value_column not in subset.columns:
        return 0.0
    return float(pd_numeric(subset[value_column]).median())


def pd_numeric(series: pd.Series) -> pd.Series:
    import pandas as pd

    return pd.to_numeric(series, errors="coerce")


def write_program_outputs(
    cells_df: pd.DataFrame, summary_df: pd.DataFrame, outputpath: str
) -> tuple[str, str]:
    """Write ``results/gene_program_summary.tsv`` and ``results/gene_program_cells.tsv``.

    Returns ``(summary_path, cells_path)``. Idempotent: rewriting produces
    byte-identical output, so a re-run does not churn the artifact hashes the
    governance ledger records.
    """
    results_dir = os.path.join(outputpath, "results")
    os.makedirs(results_dir, exist_ok=True)
    summary_path = os.path.join(results_dir, "gene_program_summary.tsv")
    cells_path = os.path.join(results_dir, "gene_program_cells.tsv")
    summary_df.to_csv(summary_path, sep="\t", index=False)
    cells_df.to_csv(cells_path, sep="\t", index=False)
    return summary_path, cells_path
