"""Read the packaged virus catalogue and turn accessions into virus names.

PLAN `CAT-03`. The catalogue (``src/viralscan/data/virus_catalog.tsv``,
generated by ``extras/build_virus_catalog.py``) holds one row per reference
accession with its species, genus, family and segment.

Two problems this solves, both of which surface as wrong rows in
``viral_summary.tsv``:

**Unnamed genes.** ``virus_grouping.virus_name_for_gene`` resolves a gene ID by
prefix-matching the hand-maintained :data:`~viralscan.constants.VIRUS_NAME_MAP`.
That covers the legacy panel's ``HUM_HERP6B_U67`` identifiers and misses
genome-scoped ones, so 13.4 % of gene IDs on the covid index resolved to no
virus and were reported as bare accessions.

**Segments.** Influenza A's eight segments are eight unrelated accessions with
no shared prefix, so one strain appeared as eight separate "viruses", and N
strains as 8 × N. Mapping every accession to its *species* makes the segments
group into one virus, and makes several strains of a species group together
too — which is what lets the reference carry real strain diversity without
fragmenting the output.

The name map is keyed by accession, both versioned (``NC_002016.1``) and bare
(``NC_002016``), so the boundary-aware prefix rule already in ``virus_grouping``
resolves ``NC_002016.1_gene1`` without any extra entries.
"""

from __future__ import annotations

import csv
import importlib.resources
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

_TSV_FILENAME = "virus_catalog.tsv"
_PACKAGE_DATA = "viralscan.data"

Row = dict[str, Any]


def _default_tsv_path() -> Path:
    """Return the packaged catalogue via importlib.resources."""
    return Path(str(importlib.resources.files(_PACKAGE_DATA).joinpath(_TSV_FILENAME)))


def catalogue_path(path: str | os.PathLike[str] | None = None) -> Path:
    return Path(path) if path is not None else _default_tsv_path()


def load_catalogue(path: str | os.PathLike[str] | None = None) -> list[Row]:
    """Load the catalogue, or return ``[]`` when it is not packaged.

    Returning empty rather than raising is deliberate: the catalogue is an
    enrichment. Every caller falls back to the existing name map, so an index
    built before the catalogue existed keeps working.
    """
    tsv_path = catalogue_path(path)
    if not tsv_path.exists():
        return []
    with open(tsv_path, newline="", encoding="utf-8") as handle:
        return [dict(row) for row in csv.DictReader(handle, delimiter="\t")]


@lru_cache(maxsize=1)
def catalog_name_map() -> dict[str, str]:
    """Return an accession → species-name map, versioned and bare keys both.

    A row with no species name is skipped rather than mapped to the empty
    string, so an incomplete catalogue degrades to the previous behaviour
    instead of renaming a virus to ``""``.
    """
    name_map: dict[str, str] = {}
    for row in load_catalogue():
        species = (row.get("species") or "").strip()
        if not species:
            continue
        versioned = (row.get("accession_version") or "").strip()
        bare = (row.get("accession") or "").strip()
        if versioned:
            name_map[versioned] = species
        if bare:
            name_map.setdefault(bare, species)
    return name_map


@lru_cache(maxsize=1)
def accession_metadata() -> dict[str, Row]:
    """Return accession → its catalogue row, versioned and bare keys both."""
    out: dict[str, Row] = {}
    for row in load_catalogue():
        versioned = (row.get("accession_version") or "").strip()
        bare = (row.get("accession") or "").strip()
        if versioned:
            out[versioned] = row
        if bare:
            out.setdefault(bare, row)
    return out


def segments_for_species(species: str) -> list[str]:
    """Accessions belonging to *species*, in segment order where declared."""
    rows = [r for r in load_catalogue() if (r.get("species") or "").strip() == species]

    def _key(row: Row) -> tuple[int, str]:
        segment = (row.get("segment") or "").strip()
        return (int(segment) if segment.isdigit() else 99, row.get("accession_version") or "")

    return [r["accession_version"] for r in sorted(rows, key=_key)]


@lru_cache(maxsize=1)
def merged_name_map() -> dict[str, str]:
    """The catalogue map merged under the legacy and anellovirus maps.

    Legacy fallback (PLAN ``MECH-A`` step 4): a Run's gene -> virus naming comes
    from its Virus Identity table. This map is used only when a Run has no table
    (a run directory made before it existed) and by the identity builder for a
    pre-v3 t2g that has no genome-accession column.

    Precedence, lowest first: the catalogue, then the packaged anellovirus genus
    map, then :data:`~viralscan.constants.VIRUS_NAME_MAP`. The legacy map wins
    because its keys name panel-specific gene-ID schemes that the catalogue does
    not describe, and the anellovirus map wins over the catalogue because
    `ANDET-05` wants one *genus* label per anellovirus genome where the
    catalogue would give the species.
    """
    from viralscan.anellovirus import merged_name_map as _anello_merged

    name_map: dict[str, str] = dict(catalog_name_map())
    name_map.update(_anello_merged())
    return name_map
