#!/usr/bin/env bash
# Bulk viral scan of GSE128078 (ME/CFS whole-blood RNA-seq) against the
# ViralScan bundled 195-virus panel.
#
# Usage:
#   Step 0 — generate SRR list (run once from login node):
#     bash scripts/bulk_viral_scan.sh --generate-srr-list
#
#   Step 1 — pilot (6 samples):
#     sbatch --array=0-5 scripts/bulk_viral_scan.sh
#
#   Step 2 — full cohort after pilot looks sane:
#     sbatch --array=0-98 scripts/bulk_viral_scan.sh
#
#   Interactive single sample (index 0):
#     SLURM_ARRAY_TASK_ID=0 bash scripts/bulk_viral_scan.sh
#
# Requires:
#   - build_bundled_panel_ref.py output: $REFDIR/panel.idx + panel.t2g
#   - test_viralscan conda env (has kb-python 0.29.3) on PATH
#   - $WORKDIR/srr_list.txt  (generated by --generate-srr-list)
#
# Index: combined host (Ensembl cDNA) + curated 195-virus panel + ~2,022 anellovirus
# accessions (clareaulab).  Host transcripts (ENST*) and viral gene_ids are
# quantified together; host reads compete for shared k-mers, reducing false-positive
# viral signal.  See coexpression and caveats notes in bulk_viral_summarize.py.

#SBATCH --job-name=vs_bulk_gse128078
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=04:00:00
#SBATCH --chdir=/exports/para-lipg-hpc/mdmanurung/viralscan_bulk_gse128078
#SBATCH --output=logs/vs_bulk_%A_%a.out
#SBATCH --error=logs/vs_bulk_%A_%a.err

set -euo pipefail

# ── paths (edit if your workspace differs) ────────────────────────────────────
REPO=/exports/para-lipg-hpc/mdmanurung/ViralScan
WORKDIR=/exports/para-lipg-hpc/mdmanurung/viralscan_bulk_gse128078
# Panel index: the complete host+viral build lives at viralscan_panel_ref/ref
# (P23.op1, 2026-07-02). The old $WORKDIR/ref/panel.idx is a host-less viral-only
# build (June 24 died at the Ensembl 404) — do NOT use it. Override with REFDIR=… if needed.
REFDIR=${REFDIR:-/exports/para-lipg-hpc/mdmanurung/viralscan_panel_ref/ref}
OUTDIR=$WORKDIR/out
SRR_LIST=$WORKDIR/srr_list.txt
THREADS=${SLURM_CPUS_PER_TASK:-4}

export PYTHONPATH=$REPO/src

# ── conda env ─────────────────────────────────────────────────────────────────
# Activate explicitly so SLURM jobs inherit kb on PATH even without a login shell.
CONDA_INIT=/share/software/tools/miniconda/3.10/23.3.1/etc/profile.d/conda.sh
CONDA_ENV=/exports/archive/hg-funcgenom-research/evonk/conda/envs/test_viralscan
if [[ -f $CONDA_INIT ]]; then
    # shellcheck source=/dev/null
    source "$CONDA_INIT"
    conda activate "$CONDA_ENV"
fi
command -v kb || { echo "ERROR: kb not on PATH — activate test_viralscan conda env"; exit 1; }

# ── --generate-srr-list: write $WORKDIR/srr_list.txt ─────────────────────────
if [[ "${1:-}" == "--generate-srr-list" ]]; then
    mkdir -p "$WORKDIR"
    echo "Querying ENA for study SRP187984 (GSE128078) …"
    curl -s \
        "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=SRP187984&result=read_run&fields=run_accession,fastq_ftp" \
        | tail -n+2 \
        | cut -f1 \
        > "$SRR_LIST"
    COUNT=$(wc -l < "$SRR_LIST")
    echo "Wrote $COUNT SRR accessions to $SRR_LIST"
    exit 0
fi

# ── preflight ─────────────────────────────────────────────────────────────────
[[ -f $REFDIR/panel.idx ]] || { echo "ERROR: $REFDIR/panel.idx not found — run build_bundled_panel_ref.py first"; exit 1; }
[[ -f $REFDIR/panel.t2g ]] || { echo "ERROR: $REFDIR/panel.t2g not found"; exit 1; }
[[ -f $SRR_LIST ]]         || { echo "ERROR: $SRR_LIST not found — run: bash $0 --generate-srr-list"; exit 1; }

IDX=${SLURM_ARRAY_TASK_ID:-0}
SRR=$(sed -n "$((IDX + 1))p" "$SRR_LIST")
[[ -n $SRR ]] || { echo "ERROR: no SRR at index $IDX in $SRR_LIST"; exit 1; }

echo "[$(date)] task=$IDX  SRR=$SRR"

# ── download FASTQs via ENA ───────────────────────────────────────────────────
DLDIR=$WORKDIR/fastq/$SRR
mkdir -p "$DLDIR"
cd "$DLDIR"

R1="" R2=""

# Reuse existing FASTQs if present from a prior run
mapfile -t EXISTING < <(ls "$DLDIR"/*.fastq.gz 2>/dev/null || true)
if [[ ${#EXISTING[@]} -ge 2 ]]; then
    echo "INFO: FASTQ already present in $DLDIR — skipping download"
    R1=$(printf '%s\n' "${EXISTING[@]}" | grep -E '(_1\.|_R1)' | head -1)
    R2=$(printf '%s\n' "${EXISTING[@]}" | grep -E '(_2\.|_R2)' | head -1)
fi

if [[ -z $R1 || -z $R2 ]]; then
    echo "INFO: downloading $SRR via ENA"
    # ENA may return 2 (paired) or 3 (R1;R2;unpaired) URLs — parse deliberately.
    ENA_FIELD=$(curl -s \
        "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=${SRR}&result=read_run&fields=fastq_ftp" \
        | awk 'NR==2{print $NF}')
    if [[ -z $ENA_FIELD ]]; then
        echo "ERROR: ENA returned no fastq_ftp for $SRR"
        exit 1
    fi
    # Split on ';', download each URL, pick R1/R2 by name pattern
    mapfile -t URLS < <(echo "$ENA_FIELD" | tr ';' '\n')
    for u in "${URLS[@]}"; do
        u="${u// /}"          # strip any whitespace (ENA field edge cases)
        [[ -n $u ]] || continue
        wget -q "ftp://$u"
    done
    mapfile -t FQ < <(ls "$DLDIR"/*.fastq.gz 2>/dev/null || true)
    R1=$(printf '%s\n' "${FQ[@]}" | grep -E '(_1\.|_R1)' | head -1)
    R2=$(printf '%s\n' "${FQ[@]}" | grep -E '(_2\.|_R2)' | head -1)
fi

[[ -f $R1 ]] || { echo "ERROR: R1 not found in $DLDIR after download"; exit 1; }
[[ -f $R2 ]] || { echo "ERROR: R2 not found in $DLDIR after download (single-end? check ENA metadata)"; exit 1; }
echo "INFO: R1=$R1"
echo "INFO: R2=$R2"

# ── kb count -x BULK ─────────────────────────────────────────────────────────
SAMPLE_OUT=$OUTDIR/$SRR
mkdir -p "$SAMPLE_OUT"

echo "INFO: running kb count -x BULK → $SAMPLE_OUT"
kb count \
    -i "$REFDIR/panel.idx" \
    -g "$REFDIR/panel.t2g" \
    --overwrite \
    -o "$SAMPLE_OUT" \
    -x BULK \
    --parity paired \
    --h5ad \
    -t "$THREADS" \
    "$R1" "$R2"

# ── quick sanity gate ─────────────────────────────────────────────────────────
RUN_INFO=$SAMPLE_OUT/run_info.json
[[ -f $RUN_INFO ]] || { echo "ERROR: run_info.json missing — kb count may have failed"; exit 1; }
N_PSEUDO=$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); print(d.get('n_pseudoaligned',0))" "$RUN_INFO")
echo "INFO: n_pseudoaligned=$N_PSEUDO"
if [[ $N_PSEUDO -eq 0 ]]; then
    echo "WARNING: n_pseudoaligned=0 — no viral reads detected (expected for most blood samples)"
fi

echo "[$(date)] Done: $SRR"
