#!/usr/bin/env bash
# P22.10 — ViralScan EBV re-run WITH 10x v2 whitelist (matched-barcode run)
#
# Re-runs viralscan on SRR12682296 (LCL_777_B958 / EBV) with the canonical
# 10x v2 barcode whitelist (-w) so barcode correction matches the paper's
# CellRanger space. Writes to a NEW output directory (out_full_depth_wl) to
# preserve the P22.4 no-whitelist run at out_full_depth.
#
# --mem=128G is required: the full-depth EBV run has 61.6M BUS records and
# OOM'd at 32G during multimap. The P22.4 run confirmed 128G holds.
#
# Requires the test_viralscan conda env (provides kb, snakemake):
#   source /exports/archive/hg-funcgenom-research/evonk/conda/envs/test_viralscan/etc/conda/activate.d/env_vars.sh
#   OR: prepend the bin/ directory to PATH (done below).
#
# Submit:
#   sbatch scripts/slurm_viralscan_ebv_wl.sh
#
# After completion, find outputs at:
#   $OUTDIR/lcl_5lines/SRR12682296/kb-python/counts_unfiltered/adata.h5ad
#   $OUTDIR/lcl_5lines/SRR12682296/kb-python/counts_unfiltered/adata_multimap.h5ad
#
#SBATCH -J vs_ebv_wl_p22.10
#SBATCH --cpus-per-task=8
#SBATCH --mem=128G
#SBATCH --time=12:00:00
#SBATCH -o logs/vs_ebv_wl_%j.log
#SBATCH -e logs/vs_ebv_wl_%j.err

set -euo pipefail

# ── Paths ─────────────────────────────────────────────────────────────────────
REPO=/exports/para-lipg-hpc/mdmanurung/ViralScan
VS_CONDA_ENV=/exports/archive/hg-funcgenom-research/evonk/conda/envs/test_viralscan
VS_ROOT=/exports/para-lipg-hpc/mdmanurung/viralscan_showcase

# Prepend conda env bin so kb/snakemake are on PATH
export PATH="$VS_CONDA_ENV/bin:$PATH"
export PYTHONPATH="$REPO/src:${PYTHONPATH:-}"

# Reference (same as P22.4)
REFDIR=/exports/archive/hg-funcgenom-research/evonk/old/intern/fasta_viruses/Serratus/transcriptome_human_hhv6_v2
VS_INDEX=$REFDIR/index_serratus.idx
VS_T2G=$REFDIR/t2g_serratus.txt
VS_VIRAL_GTF=$VS_ROOT/data/ref/viral_from_index.gtf  # already generated by P22.4

# Input data (already downloaded from P22.4)
ID=lcl_5lines
SRR=SRR12682296
TECH=10xv2
VS_THREADS=8
VS_SE_THRESHOLD=10

R1=$VS_ROOT/data/$ID/${SRR}/${SRR}_1.fastq.gz
R2=$VS_ROOT/data/$ID/${SRR}/${SRR}_2.fastq.gz

# 10x v2 whitelist (737,280 barcodes; extracted in Step 0)
WHITELIST=$REPO/ref/10x_version2_whitelist.txt

# New output directory (separate from P22.4)
OUTDIR=$VS_ROOT/out_full_depth_wl

mkdir -p "$OUTDIR/$ID" "$REPO/logs"

# ── Verify prerequisites ───────────────────────────────────────────────────────
for f in "$R1" "$R2" "$WHITELIST" "$VS_INDEX" "$VS_T2G" "$VS_VIRAL_GTF"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: required file not found: $f" >&2
        exit 1
    fi
done
command -v kb || { echo "ERROR: kb not on PATH — conda env bin not prepended correctly"; exit 1; }

echo "[$(date)] Prerequisites OK."
echo "  R1:        $R1"
echo "  R2:        $R2"
echo "  Whitelist: $WHITELIST ($(wc -l < "$WHITELIST") barcodes)"
echo "  Index:     $VS_INDEX"
echo "  T2G:       $VS_T2G"
echo "  Output:    $OUTDIR/$ID/"

# ── Run ViralScan ──────────────────────────────────────────────────────────────
DONE_FILE="$OUTDIR/$ID/$SRR/log/multimap.done"

if [[ -f "$DONE_FILE" ]]; then
    echo "  [SKIP] ViralScan already completed (multimap.done exists at $DONE_FILE)"
else
    echo "[$(date)] Running viralscan (10xv2, -w whitelist, host-conservative, confidence) ..."
    python "$REPO/src/viralscan/menu.py" \
        -i "$VS_INDEX" \
        -t "$VS_T2G" \
        -gtf "$VS_VIRAL_GTF" \
        -o "$OUTDIR/$ID/" \
        -s1 "$R1" -s2 "$R2" \
        -x "$TECH" \
        -w "$WHITELIST" \
        -c "$VS_THREADS" \
        --se-threshold "$VS_SE_THRESHOLD" \
        --detection-threshold 1 \
        --multimap-method host-conservative \
        --multimap-primary-call confidence \
        --yes

    echo "[$(date)] viralscan run complete."
fi

# ── Quick summary ──────────────────────────────────────────────────────────────
SUMMARY="$OUTDIR/$ID/$SRR/results/viral_summary.tsv"
if [[ -f "$SUMMARY" ]]; then
    echo "[$(date)] Viral summary:"
    cat "$SUMMARY"
else
    echo "WARNING: viral_summary.tsv not written — viralscan may have failed"
fi

ADATA="$OUTDIR/$ID/$SRR/kb-python/counts_unfiltered/adata.h5ad"
ADATA_MM="$OUTDIR/$ID/$SRR/kb-python/counts_unfiltered/adata_multimap.h5ad"
[[ -f "$ADATA"    ]] && echo "[$(date)] adata.h5ad found: $ADATA"
[[ -f "$ADATA_MM" ]] && echo "[$(date)] adata_multimap.h5ad found: $ADATA_MM"

echo "[$(date)] P22.10 ViralScan-wl run complete."
echo "  Outputs: $OUTDIR/$ID/$SRR/"
