#!/usr/bin/env bash
# Full-depth validation — three benchmark scRNA-seq datasets.
#
# Usage (submit all three as a SLURM array):
#   sbatch --array=0-2 scripts/slurm_full_depth_validation.sh
#
# Or run a single dataset interactively (index 0=HHV-6, 1=EBV, 2=HSV-1):
#   SLURM_ARRAY_TASK_ID=0 bash scripts/slurm_full_depth_validation.sh
#
# After all three jobs finish, run the summary helper at the bottom of this
# file to produce BENCHMARK_COMPARISON_full_depth.tsv.
#
# Results are written to $VS_OUT/<id>/<SRR>/ in the standard viralscan layout.
# Compare viral_summary.tsv against BENCHMARK_COMPARISON.md published rates.

#SBATCH --job-name=vs_val
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=08:00:00
#SBATCH --output=%x_%A_%a.out
#SBATCH --error=%x_%A_%a.err

set -euo pipefail

# ── paths (edit if your workspace differs) ───────────────────────────────────
VS_ROOT=/exports/para-lipg-hpc/mdmanurung/viralscan_showcase
VS_DATA=$VS_ROOT/data
VS_OUT=$VS_ROOT/out_full_depth
VS_THREADS=${SLURM_CPUS_PER_TASK:-8}
VS_SE_THRESHOLD=10

REFDIR=/exports/archive/hg-funcgenom-research/evonk/old/intern/fasta_viruses/Serratus/transcriptome_human_hhv6_v2
VS_INDEX=$REFDIR/index_serratus.idx
VS_T2G=$REFDIR/t2g_serratus.txt
VS_VIRAL_GTF=$VS_DATA/ref/viral_from_index.gtf   # generated by showcase_runbook §2

# ── dataset registry (indices 0-2 match SLURM_ARRAY_TASK_ID) ─────────────────
declare -a IDS=(        hhv6_carT_ref   lcl_5lines      hsv1_fibroblast )
declare -a SRRS=(       SRR20710641     SRR12682296     SRR8315713      )
declare -a TECHS=(      10xv3           10xv2           DROPSEQ         )
declare -a EXPECTED=(   "HHV-6B"        "EBV"           "HSV-1"         )

IDX=${SLURM_ARRAY_TASK_ID:-0}
ID=${IDS[$IDX]}
SRR=${SRRS[$IDX]}
TECH=${TECHS[$IDX]}
EXPECT=${EXPECTED[$IDX]}

echo "[$(date)] Starting job $IDX: id=$ID  srr=$SRR  tech=$TECH  expect=$EXPECT"

# ── viralscan env ─────────────────────────────────────────────────────────────
# Prefer the conda env's kb/snakemake but use the repo's viralscan source.
REPO=/exports/para-lipg-hpc/mdmanurung/ViralScan
export PYTHONPATH=$REPO/src
command -v kb    || { echo "ERROR: kb not on PATH — activate viralscan conda env"; exit 1; }
command -v snakemake || { echo "ERROR: snakemake not on PATH"; exit 1; }

# ── pre-flight ────────────────────────────────────────────────────────────────
[[ -f $VS_INDEX ]]     || { echo "ERROR: index not found at $VS_INDEX"; exit 1; }
[[ -f $VS_T2G ]]       || { echo "ERROR: t2g not found at $VS_T2G"; exit 1; }
[[ -f $VS_VIRAL_GTF ]] || {
    echo "INFO: generating viral GTF from t2g (one-time)"
    mkdir -p "$(dirname "$VS_VIRAL_GTF")"
    grep -v '^ENST' "$VS_T2G" | awk -F'\t' '{print $2}' | sort -u | \
      awk 'BEGIN{OFS="\t"}{print $1,"ViralScan","exon","1","1",".","+",".","gene_id \""$1"\";"}' \
      > "$VS_VIRAL_GTF"
    echo "INFO: wrote $(wc -l < "$VS_VIRAL_GTF") viral genes to $VS_VIRAL_GTF"
}

mkdir -p "$VS_DATA/$ID/$SRR" "$VS_OUT/$ID"

# ── download (ENA-first, SRA fallback) ───────────────────────────────────────
DLDIR=$VS_DATA/$ID/$SRR
cd "$DLDIR"

R1="" R2=""

# Check whether we already have paired FASTQs from a previous run
mapfile -t EXISTING < <(ls "$DLDIR"/*.fastq.gz 2>/dev/null || true)
if [[ ${#EXISTING[@]} -ge 2 ]]; then
    echo "INFO: FASTQ already present in $DLDIR — skipping download"
    R1=$(printf '%s\n' "${EXISTING[@]}" | grep -E '(_1\.|_R1)' | head -1)
    R2=$(printf '%s\n' "${EXISTING[@]}" | grep -E '(_2\.|_R2)' | head -1)
fi

if [[ -z $R1 || -z $R2 ]]; then
    echo "INFO: downloading $SRR via ENA"
    ENA_URLS=$(curl -s \
      "https://www.ebi.ac.uk/ena/portal/api/filereport?accession=${SRR}&result=read_run&fields=fastq_ftp" \
      | awk 'NR==2{print $NF}' | tr ';' '\n')
    if [[ -n $ENA_URLS ]]; then
        for u in $ENA_URLS; do wget -q "ftp://$u"; done
    else
        echo "INFO: ENA empty; falling back to SRA prefetch"
        prefetch -O "$DLDIR" "$SRR"
        fasterq-dump --split-files --include-technical \
            -e "$VS_THREADS" -O "$DLDIR" "$DLDIR/$SRR/$SRR.sra"
        pigz -p "$VS_THREADS" "$DLDIR"/*.fastq
    fi
    mapfile -t FQ < <(ls "$DLDIR"/*.fastq.gz)
    R1=$(printf '%s\n' "${FQ[@]}" | grep -E '(_1\.|_R1)' | head -1)
    R2=$(printf '%s\n' "${FQ[@]}" | grep -E '(_2\.|_R2)' | head -1)
fi

[[ -f $R1 ]] || { echo "ERROR: R1 not found after download in $DLDIR"; exit 1; }
[[ -f $R2 ]] || { echo "ERROR: R2 not found after download in $DLDIR"; exit 1; }

echo "INFO: R1=$R1"
echo "INFO: R2=$R2"

# ── run viralscan ─────────────────────────────────────────────────────────────
# --yes skips the interactive overwrite prompt (added in recent commit)
python "$REPO/src/viralscan/menu.py" \
    -i "$VS_INDEX" \
    -t "$VS_T2G" \
    -gtf "$VS_VIRAL_GTF" \
    -o "$VS_OUT/$ID/" \
    -s1 "$R1" -s2 "$R2" \
    -x "$TECH" \
    -c "$VS_THREADS" \
    --se-threshold "$VS_SE_THRESHOLD" \
    --detection-threshold 1 \
    --multimap-method host-conservative \
    --multimap-primary-call confidence \
    --yes

# ── quick validation gate ─────────────────────────────────────────────────────
SAMPLE_DIR=$(basename "$R1" | sed 's/_.*//') # R1-prefix naming convention
SUMMARY=$VS_OUT/$ID/$SAMPLE_DIR/results/viral_summary.tsv

if [[ -f $SUMMARY ]]; then
    echo ""
    echo "=== viral_summary.tsv for $ID / $SRR ==="
    column -t -s$'\t' "$SUMMARY" | sort -k2 -nr | head -10
    echo ""
    # Check that the expected virus is present
    if grep -qi "$EXPECT" "$SUMMARY"; then
        echo "GATE PASS: $EXPECT found in viral_summary.tsv"
    else
        echo "GATE FAIL: $EXPECT NOT found in viral_summary.tsv — check chemistry / read order"
        exit 1
    fi
else
    echo "ERROR: viral_summary.tsv not written — viralscan may have failed"
    exit 1
fi

echo "[$(date)] Job $IDX complete: $ID / $SRR"


# =============================================================================
# SUMMARY HELPER — run after all three jobs finish:
#
#   bash scripts/slurm_full_depth_validation.sh --summarize
#
# Writes BENCHMARK_COMPARISON_full_depth.tsv in $VS_ROOT.
# =============================================================================
if [[ "${1:-}" == "--summarize" ]]; then
    OUT_TSV=$VS_ROOT/BENCHMARK_COMPARISON_full_depth.tsv
    printf 'id\tsrr\ttechnology\texpected_virus\tpct_infected\tinfected_cells\ttotal_umi\tumi_per_10k\n' \
        > "$OUT_TSV"
    for i in 0 1 2; do
        id=${IDS[$i]}; srr=${SRRS[$i]}; tech=${TECHS[$i]}; exp=${EXPECTED[$i]}
        sample_prefix=$(ls "$VS_OUT/$id/" 2>/dev/null | head -1)
        tsv=$VS_OUT/$id/$sample_prefix/results/viral_summary.tsv
        if [[ -f $tsv ]]; then
            # pull the row for the expected virus (case-insensitive partial match)
            row=$(grep -i "$exp" "$tsv" | sort -t$'\t' -k2 -nr | head -1)
            pct=$(echo "$row" | awk -F'\t' '{print $4}')
            cells=$(echo "$row" | awk -F'\t' '{print $3}')
            umi=$(echo "$row" | awk -F'\t' '{print $2}')
            per10k=$(echo "$row" | awk -F'\t' '{print $5}')
            printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
                "$id" "$srr" "$tech" "$exp" "$pct" "$cells" "$umi" "$per10k" >> "$OUT_TSV"
        else
            printf '%s\t%s\t%s\t%s\tMISSING\t-\t-\t-\n' "$id" "$srr" "$tech" "$exp" >> "$OUT_TSV"
        fi
    done
    echo "Wrote $OUT_TSV"
    column -t -s$'\t' "$OUT_TSV"
    exit 0
fi
