#!/usr/bin/env python3
"""Write an ``@EXPLICIT`` conda spec from an environment's ``conda-meta`` (REL-03).

Equivalent to ``conda list --explicit --md5 -n <env>`` for machines with no conda
binary on PATH: every conda-meta record carries the package ``url`` and ``md5``.
Lines are sorted by URL so the output is deterministic. Pip-installed packages
have no conda-meta record and are not listed (as with ``conda list --explicit``).

    python scripts/write_explicit_lock.py <env_prefix> [-o environment.explicit.txt]

Reinstall with ``conda create --name <env> --file environment.explicit.txt``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HEADER = (
    "# This file may be used to create an environment using:\n"
    "# $ conda create --name <env> --file <this file>\n"
    "# platform: linux-64\n"
    "# generated by scripts/write_explicit_lock.py (sorted by URL; "
    "equivalent to `conda list --explicit --md5`)\n"
    "@EXPLICIT\n"
)


def explicit_lines(env: Path) -> list[str]:
    meta = env / "conda-meta"
    if not meta.is_dir():
        sys.exit(f"error: {meta} is not a directory")
    lines = []
    for path in sorted(meta.glob("*.json")):
        rec = json.loads(path.read_text())
        url, md5 = rec.get("url"), rec.get("md5")
        if not url or not md5 or not url.startswith("https://"):
            sys.exit(f"error: {path.name} lacks a package https url/md5")
        lines.append(f"{url}#{md5}")
    return sorted(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("env", type=Path, help="conda environment prefix")
    ap.add_argument("-o", "--output", type=Path, help="default: stdout")
    args = ap.parse_args()
    text = HEADER + "\n".join(explicit_lines(args.env)) + "\n"
    if args.output:
        args.output.write_text(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
